### ISSUE TITLE
Provide prometheus metrics

### ISSUE THREAD

**Issue by 2opremio** [microservices-demo/microservices-demo#422]
This would be very useful to demo Weave Cortex: https://github.com/weaveworks/cortex

To tie the knot the microservices-demo deployments should also allow deploying prometheus forwarders to WeaveCloud, see for instance how it's done for Kubernetes: https://github.com/weaveworks/cortex#getting-started-with-weave-cloud--kubernetes

**Comment by errordeveloper** [comment]
I think this is mostly done, I've tested it with Kubernetes. Please try deploying https://github.com/microservices-demo/microservices-demo/blob/master/deploy/kubernetes/complete-demo.yaml along with cloud.weave.works/k8s/cortex.yaml. We do need to double check how many of the services are covered, surely front-end is (as of https://github.com/microservices-demo/front-end/pull/25).

**Comment by pidster** [comment]
The 3 Spring services already export Prom metrics on `/prometheus`.
The Go kit services export basic metrics too.

**Comment by errordeveloper** [comment]
We probably wanna add https://github.com/prometheus/mysqld_exporter and https://github.com/dcu/mongodb_exporter.

**Comment by rade** [comment]
What's left to do here?

When I was demoing the sock shop at re:invent, I struggled to find many meaningful metrics.

**Comment by 2opremio** [comment]
They are not provided in some deployments like ECS (at re:Invent you saw it under a K8s deployment) but maybe we should create a separate ticket for that?

**Comment by rade** [comment]
Even under k8s there didn't seem to be RED metrics for all the services.

**Comment by rade** [comment]
To be clear, we want the same set of [RED metrics](https://www.weave.works/prometheus-and-kubernetes-monitoring-your-applications/) for all services.

Later, in separate issues, we may wish to add some service specific metrics.

**Comment by lukemarsden** [comment]
They're currently working on adding metrics to the front-end, and tidying up some naming.

**Comment by lukemarsden** [comment]
Let's list all the available metrics at the end of this work, here in this issue.

**Comment by philwinder** [comment]
Current progress:
Creating RED metrics for all services. All metrics will have the base name `request_duration_seconds`. This is a histogram with the usual `_bucket`, `_count` and `_sum` metrics.

My kubecon demo will demonstrate the sock shop with these prometheus metrics. I will run the load test in order to generate load to see the metrics rise. I will (if possible) create alerts to monitor these metrics.

Monitoring/alerting scenarios:
- Service is dead (Manually kill a service, watch it 500. Alert.)
- Spike in requests (massive load test, latency increases, alert?)

This will be repeated in weave cloud.

Prior to this the presentation will discuss how these metrics were integrated and the sock-shop in general. 

Tasks complete:
- [x] Front End
- [x] User
- [x] Payment
- [x] Catalogue
- [x] Carts
- [x] Orders
- [x] Shipping
- [x] Load test is appropriate?
- [x] Documentation showing `request_duration_seconds` metric.
- [x] Add alerts to sock shop
- [x] Create scenarios

**Comment by rade** [comment]
> All metrics will have the name `request_duration_seconds`.

Just to check, these are histogram bucket things (whatever prom calls them), so you get `request_duration_seconds_count`, `request_duration_seconds_sum` and `request_duration_seconds_bucket`, right?

**Comment by nustiueudinastea** [comment]
@rade indeed. I know count and sum are provided, and I can't recall bucket, but probably that one as well.

**Comment by philwinder** [comment]
This work was completed in a large number of merges across all the repos.
See https://github.com/microservices-demo/microservices-demo/blob/master/deploy/kubernetes/README.md for some simple documentation.
