### ISSUE TITLE
Deploy docs for kubernetes should take advantage of Weave Flux

### ISSUE THREAD

**Issue by vlal-zz** [microservices-demo/microservices-demo#434]
- [x] Create terraform files to create a cluster of 3+ instances 
   - [x] Setup kubernetes on the cluster

Ssh into the master node
- [x] Setup Weave net on master node
- [x] Install and setup Weave scope
- [x] Install fluxd on master node
- [x] Install fluxctl on master node
- [x] Integrate slack
- [x] Create and populate flux.conf file
- [x] Deploy sockshop
- [x] Set fluxctl automate 

References
* https://www.weave.works/guides/cloud-guide-part-2-deploy-continuous-delivery/

**Comment by vlal-zz** [comment]
@pidster flux requires adding a private key to microservices-demo repo but I don’t have permission to do that. Any chance I can get access, or access to any private key we already have there?

**Comment by vlal-zz** [comment]
Also do we want to configure a slack hook? If so that'll require adding the webhook integration to the channel.

**Comment by vlal-zz** [comment]
@pidster ping^^

**Comment by philwinder** [comment]
@vlal @pidster 
When we've got issues like #360, can I suggest that adding flux to the documentation is a complication we don't need right now?

**Comment by nustiueudinastea** [comment]
@pidster @vlal are we still doing this? This should be fairly straightforward to achieve if we don't do any Slack integration. We only need to add a standalone flux installation to the existing deploy_doc/terraform stuff. Taking in consideration the overall goals of this project, it's good for the project and it's good for Weave.

Update: I will be difficult to add Flux to the automated steps in deploy_doc because of the requirement to have a private key that has access to the microservices-demo repo. A way of doing this is to only add instructions that are not tested by deploy_doc, but that allows the user to fork the microservices-demo repo and use their own key to configure Flux.

**Comment by vlal-zz** [comment]
@nustiueudinastea I agree, adding flux to the deploy docs might be too difficult. So that begs the question whether we should add it to the docs but leave it untested. 

@pidster thoughts?

**Comment by jasonrichardsmith** [comment]
Just add link to flux guide.
https://www.weave.works/guides/cloud-guide-part-2-deploy-continuous-delivery/

no automated deploy docs

**Comment by vlal-zz** [comment]
Fixed microservices-demo/microservices-demo.github.io#53
