### ISSUE TITLE
sock-shop deploy should be moved to ecs-cli.

### ISSUE THREAD

**Issue by vlal-zz** [microservices-demo/microservices-demo#455]
It is an official part of AWS Blox now

/cc @frankscholten @jasonrichardsmith

**Comment by frankscholten** [comment]
Currently blocked on https://github.com/aws/amazon-ecs-cli/issues/184

**Comment by nustiueudinastea** [comment]
At the moment the only thing blocking this issue is DNS discovery between depending containers. The memory issue has been solved and the containers can be started using two separate compose files, as discovered by @frankscholten.

The reason why DNS does not work is because of the split in two compose files, and linking does not work across compose files.

**Comment by nustiueudinastea** [comment]
Related ecs-cli issues: https://github.com/aws/amazon-ecs-cli/issues/87

**Comment by pidster** [comment]
If it's using Weave Net, linking shouldn't matter.

**Comment by vlal-zz** [comment]
nonissue, sock shop was moved to GKE
