### ISSUE TITLE
manifests-logging image pull error

### ISSUE THREAD

**Issue by ntlzthm8** [microservices-demo/microservices-demo#849]
ELK docker hub don't have latest tag to images, only special versions

and we have error after

`kubectl create -f deploy/kubernetes/manifests-logging`

```
Failed to pull image "kibana": rpc error: code = Unknown desc = Error response from daemon: manifest for kibana:latest not found
Failed to pull image "elasticsearch": rpc error: code = Unknown desc = Error response from daemon: manifest for elasticsearch:latest not found
```

To fix this problem, need edit files in deploy/kubernetes/manifests-logging

kibana.yml

```
    spec:
      containers:
       - image: kibana:7.12.1
```

elasticsearch.yml

```
    spec:
      containers:
       - image: elasticsearch:7.12.1
```

**Comment by elieserr** [comment]
Hi, @TidalPoo would you like to try adding these changes?

**Comment by ntlzthm8** [comment]
> Hi, @TidalPoo would you like to try adding these changes?

i add these changes to my local deployment

but we have a new error)
elasticsearch 7+ need `discovery.type: single-node` configure to start elastic in local node

i did this change and it all worked!)

**Comment by rodrmartinez** [comment]
@TidalPoo would you like to open a PR with those changes?

**Comment by ntlzthm8** [comment]
> @TidalPoo would you like to open a PR with those changes?

how can i do this?

**Comment by rodrmartinez** [comment]
@TidalPoo just open a Pull Request from a branch that includes the changes you made in you local deployment

**Comment by giannoul** [comment]
As per:
* https://github.com/elastic/elasticsearch-docker/issues/75
* https://github.com/elastic/elasticsearch-docker/issues/83

Elasticsearch images do not support `latest` tag. This must be the root cause regarding the the missing `latest` tags for the `elasticsearch` and `kibana` images  

Since the code here:
* https://github.com/giannoul/microservices-demo/blame/master/deploy/kubernetes/manifests-logging/elasticsearch.yml#L17

is more than 5 years old, this must be why it does not work out of the box. Also, please note that since fluentd is too old (for details [check here](https://github.com/microservices-demo/microservices-demo/issues/870)), using the latest images for  `elasticsearch` and `kibana` will lead to no logs being pushed to `elasticsearch`.

**Comment by ntlzthm8** [comment]
Yes, I have already been convinced by my own experience. thx
