### ISSUE TITLE
prometheus does not show application metrics

### ISSUE THREAD

**Issue by emerelte** [microservices-demo/microservices-demo#850]
Running on minikube, after applying:
`kubectl create -f deploy/kubernetes/complete-demo.yaml`
and
`kubectl create -f deploy/kubernetes/manifests-monitoring`
I cant see the sock-shop metrics in Prometheus, e.g. request_duration_seconds is not visible at all.
The appropriate targets are dropped thus not active in service discovery:
```
    kubernetes-apiservers (1 / 23 active targets)
    kubernetes-cadvisor (1 / 1 active targets)
    kubernetes-nodes (1 / 1 active targets)
    kubernetes-pods (1 / 32 active targets)
    kubernetes-service-endpoints (3 / 21 active targets)
    kubernetes-services (0 / 23 active targets)
```
What should be done to fix that problem?

**Comment by rodrmartinez** [comment]
Hi @emerelte , the services are not shown because they don't have the `prometheus.io/scrape annotation`, once [ this](https://github.com/microservices-demo/microservices-demo/pull/847) PR is merged them will be shown. Meanwhile you can try it adding this annotation to the services:
```
kind: Service
metadata:  
       prometheus.io/scrape: 'true'
```

**Comment by emerelte** [comment]
Thank you, the solution worked for me

**Comment by jldiaz-uniovi** [comment]
@rodrmartinez  Thanks! Worked for me too, to see the "Sock-Shop Analytics" and "Sock-Shop Performances". However, the dashboards "Sock-Shop Resources" and "Kubernetes Pod resources" still show no data.

In fact, the metrics those dashboards try to show (eg: `container_memory_working_set_bytes` or any `container_*`) are not available in Prometheus, so I guess something else is necessary in order to Prometheus scrape that data. I'm running on AWS EKS.
